#define REDIS_GIT_SHA1 "fa6e018c"
#define REDIS_GIT_DIRTY "151"
#define REDIS_BUILD_ID "debian-1787810224"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
